// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7kBA2jtJi6ZEqjREC_6UEoR2Mr9Fljo',
    appId: '1:96545541122:web:5e3bec245c691a1fe1eb1b',
    messagingSenderId: '96545541122',
    projectId: 'aplikasipm-dbf39',
    authDomain: 'aplikasipm-dbf39.firebaseapp.com',
    storageBucket: 'aplikasipm-dbf39.appspot.com',
    measurementId: 'G-LXXS7CQ2WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYMknKMW49KxuV3VU8kpCvYDD1IwlB4ik',
    appId: '1:96545541122:android:f3a30d8f4494861ce1eb1b',
    messagingSenderId: '96545541122',
    projectId: 'aplikasipm-dbf39',
    storageBucket: 'aplikasipm-dbf39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJXUYWvUew4HzldRtRe9aS8OFzudLYqew',
    appId: '1:96545541122:ios:7f6af681baa97583e1eb1b',
    messagingSenderId: '96545541122',
    projectId: 'aplikasipm-dbf39',
    storageBucket: 'aplikasipm-dbf39.appspot.com',
    iosBundleId: 'com.example.praktikummodul1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJXUYWvUew4HzldRtRe9aS8OFzudLYqew',
    appId: '1:96545541122:ios:551dc249125063fde1eb1b',
    messagingSenderId: '96545541122',
    projectId: 'aplikasipm-dbf39',
    storageBucket: 'aplikasipm-dbf39.appspot.com',
    iosBundleId: 'com.example.praktikummodul1.RunnerTests',
  );
}
