name: praktikummodul1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  get_storage: 2.1.1
  image_picker: ^0.8.4+4
  webview_flutter: ^3.0.0
  http: ^1.0.0
  dio: ^5.3.2
  get: 4.6.6
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  google_sign_in: ^5.2.1
  flutter_signin_button: ^2.0.0
  appwrite: ^11.0.1
  dart_appwrite: ^10.1.0
  cupertino_icons: ^1.0.2
  # mockito
  mockito: ^5.4.2
  # build_runner
  build_runner: ^2.4.6

  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  path: ^1.8.0
  image: ^3.0.2

integration_test:
sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.16.0

flutter:
  uses-material-design: true

